In [1]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
from os import path
import pandas as pd
df=pd.read_csv("/content/student_performance_dataset_100x10.csv")
df.head()

,student_id,age,gender,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
0,S001,23,Male,4.6,72,7,5.5,6.2,78,66
1,S002,22,Male,18.2,57,4,4.9,2.6,73,62
2,S003,19,Female,9.3,92,8,8.1,1.0,86,77
3,S004,21,Female,10.7,68,9,5.0,3.7,57,66
4,S005,22,Female,23.4,84,12,5.1,7.5,40,70

In [7]:
df.shape

(100, 10)

In [8]:
df.dtypes

student_id                object
age                        int64
gender                    object
study_hours_per_week     float64
attendance_percent         int64
assignments_completed      int64
sleep_hours              float64
internet_usage_hours     float64
previous_score             int64
final_score                int64
dtype: object

In [11]:
df.tail(10)

,student_id,age,gender,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
90,S091,20,Male,5.7,65,8,7.2,6.8,93,70
91,S092,18,Female,20.5,99,10,8.7,4.5,66,84
92,S093,22,Male,25.3,75,8,4.6,2.6,78,89
93,S094,22,Male,28.0,98,8,7.1,6.3,46,77
94,S095,23,Female,26.0,66,10,7.4,4.4,40,70
95,S096,21,Female,11.7,61,6,6.0,5.9,53,58
96,S097,21,Male,14.9,75,8,6.0,7.8,60,70
97,S098,24,Male,19.8,89,11,6.4,2.3,58,80
98,S099,21,Female,22.2,68,8,7.0,7.5,63,78
99,S100,21,Male,4.7,95,7,7.7,3.2,35,53

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             100 non-null    object
 1   age                    100 non-null    int64
 2   gender                 100 non-null    object
 3   study_hours_per_week   100 non-null    float64
 4   attendance_percent     100 non-null    int64
 5   assignments_completed  100 non-null    int64
 6   sleep_hours            100 non-null    float64
 7   internet_usage_hours   100 non-null    float64
 8   previous_score         100 non-null    int64
 9   final_score            100 non-null    int64
dtypes: float64(3), int64(5), object(2)
memory usage: 7.9+ KB

In [13]:
df.describe()

,age,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
count,100.00000,100.000000,100.00000,100.000000,100.000000,100.000000,100.00000,100.000000
mean,20.90000,15.733000,79.05000,8.000000,6.566000,4.792000,66.67000,72.120000
std,1.95143,7.073511,12.02134,2.391061,1.284737,2.076646,18.19982,11.116718
min,18.00000,4.300000,56.00000,4.000000,4.600000,1.000000,35.00000,45.000000
25%,19.00000,9.775000,70.00000,6.000000,5.475000,2.900000,50.75000,64.750000
50%,21.00000,16.450000,81.00000,8.000000,6.500000,4.700000,66.00000,71.000000
75%,22.25000,22.050000,88.00000,10.000000,7.525000,6.600000,83.25000,80.250000
max,24.00000,28.000000,100.00000,12.000000,8.900000,8.000000,95.00000,100.000000

In [14]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
study_hours_per_week     0
attendance_percent       0
assignments_completed    0
sleep_hours              0
internet_usage_hours     0
previous_score           0
final_score              0
dtype: int64

In [15]:
df = pd.get_dummies(df, columns=["gender"], dtype=int)
df.head()

,student_id,age,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score,gender_Female,gender_Male
0,S001,23,4.6,72,7,5.5,6.2,78,66,0,1
1,S002,22,18.2,57,4,4.9,2.6,73,62,0,1
2,S003,19,9.3,92,8,8.1,1.0,86,77,1,0
3,S004,21,10.7,68,9,5.0,3.7,57,66,1,0
4,S005,22,23.4,84,12,5.1,7.5,40,70,1,0