In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from os import path
import pandas as pd
df=pd.read_csv("/content/student_performance_dataset_100x10.csv")
df.head()

,student_id,age,gender,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
0,S001,23,Male,4.6,72,7,5.5,6.2,78,66
1,S002,22,Male,18.2,57,4,4.9,2.6,73,62
2,S003,19,Female,9.3,92,8,8.1,1.0,86,77
3,S004,21,Female,10.7,68,9,5.0,3.7,57,66
4,S005,22,Female,23.4,84,12,5.1,7.5,40,70

In [ ]:
df.shape

(100, 10)

In [ ]:
df.dtypes

student_id                object
age                        int64
gender                    object
study_hours_per_week     float64
attendance_percent         int64
assignments_completed      int64
sleep_hours              float64
internet_usage_hours     float64
previous_score             int64
final_score                int64
dtype: object

In [ ]:
df.tail(10)

,student_id,age,gender,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
90,S091,20,Male,5.7,65,8,7.2,6.8,93,70
91,S092,18,Female,20.5,99,10,8.7,4.5,66,84
92,S093,22,Male,25.3,75,8,4.6,2.6,78,89
93,S094,22,Male,28.0,98,8,7.1,6.3,46,77
94,S095,23,Female,26.0,66,10,7.4,4.4,40,70
95,S096,21,Female,11.7,61,6,6.0,5.9,53,58
96,S097,21,Male,14.9,75,8,6.0,7.8,60,70
97,S098,24,Male,19.8,89,11,6.4,2.3,58,80
98,S099,21,Female,22.2,68,8,7.0,7.5,63,78
99,S100,21,Male,4.7,95,7,7.7,3.2,35,53

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             100 non-null    object
 1   age                    100 non-null    int64
 2   gender                 100 non-null    object
 3   study_hours_per_week   100 non-null    float64
 4   attendance_percent     100 non-null    int64
 5   assignments_completed  100 non-null    int64
 6   sleep_hours            100 non-null    float64
 7   internet_usage_hours   100 non-null    float64
 8   previous_score         100 non-null    int64
 9   final_score            100 non-null    int64
dtypes: float64(3), int64(5), object(2)
memory usage: 7.9+ KB

In [ ]:
df.describe()

,age,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score
count,100.00000,100.000000,100.00000,100.000000,100.000000,100.000000,100.00000,100.000000
mean,20.90000,15.733000,79.05000,8.000000,6.566000,4.792000,66.67000,72.120000
std,1.95143,7.073511,12.02134,2.391061,1.284737,2.076646,18.19982,11.116718
min,18.00000,4.300000,56.00000,4.000000,4.600000,1.000000,35.00000,45.000000
25%,19.00000,9.775000,70.00000,6.000000,5.475000,2.900000,50.75000,64.750000
50%,21.00000,16.450000,81.00000,8.000000,6.500000,4.700000,66.00000,71.000000
75%,22.25000,22.050000,88.00000,10.000000,7.525000,6.600000,83.25000,80.250000
max,24.00000,28.000000,100.00000,12.000000,8.900000,8.000000,95.00000,100.000000

In [ ]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
study_hours_per_week     0
attendance_percent       0
assignments_completed    0
sleep_hours              0
internet_usage_hours     0
previous_score           0
final_score              0
dtype: int64

In [ ]:
df = pd.get_dummies(df, columns=["gender"], dtype=int)
df.head()

,student_id,age,study_hours_per_week,attendance_percent,assignments_completed,sleep_hours,internet_usage_hours,previous_score,final_score,gender_Female,gender_Male
0,S001,23,4.6,72,7,5.5,6.2,78,66,0,1
1,S002,22,18.2,57,4,4.9,2.6,73,62,0,1
2,S003,19,9.3,92,8,8.1,1.0,86,77,1,0
3,S004,21,10.7,68,9,5.0,3.7,57,66,1,0
4,S005,22,23.4,84,12,5.1,7.5,40,70,1,0

# **# Lecture_12: EDA(Exploratory data analysis)**

In [1]:
import pandas as pd
df=pd.read_csv("/content/synthetic_disease_eda_dataset_20000x17.csv")

In [5]:
df.shape

(20000, 17)

In [2]:
df.head()

,Patient_ID,Visit_Date,Age,Gender,Region,Disease,Symptoms_Count,Severity_Score,BMI,Blood_Pressure_Systolic,Cholesterol_mg_dL,Blood_Glucose_mg_dL,Smoking_Status,Hospitalized,Hospital_Days,Treatment_Cost_USD,Outcome
0,P008802,2024-10-24,64,Male,Urban,Coronary Heart Disease,4,10,32.3,178,269.0,164.0,Current,No,0,2233.08,Deceased
1,P012738,2025-03-18,23,Female,Suburban,Migraine,6,7,32.8,114,151.0,75.0,Current,No,0,634.80,Improving
2,P008732,2025-05-30,50,Female,Suburban,Hypertension,5,7,31.4,178,204.0,169.0,Never,No,0,880.49,Complications
3,P003371,2025-11-13,19,Other,Urban,Influenza,6,5,15.9,111,185.0,84.0,Former,No,0,522.30,Recovered
4,P019733,2024-09-27,43,Male,Urban,Pneumonia,8,8,18.8,116,225.0,59.0,Never,No,0,1310.85,Deceased

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               20000 non-null  object
 1   Visit_Date               20000 non-null  object
 2   Age                      20000 non-null  int64
 3   Gender                   20000 non-null  object
 4   Region                   20000 non-null  object
 5   Disease                  20000 non-null  object
 6   Symptoms_Count           20000 non-null  int64
 7   Severity_Score           20000 non-null  int64
 8   BMI                      19500 non-null  float64
 9   Blood_Pressure_Systolic  20000 non-null  int64
 10  Cholesterol_mg_dL        19316 non-null  float64
 11  Blood_Glucose_mg_dL      19409 non-null  float64
 12  Smoking_Status           19662 non-null  object
 13  Hospitalized             20000 non-null  object
 14  Hospital_Days            20000 non-null  int64
 15  Treatment_Cost_USD       19755 non-null  float64
 16  Outcome                  20000 non-null  object
dtypes: float64(4), int64(5), object(8)
memory usage: 2.6+ MB

In [4]:
df.tail()

,Patient_ID,Visit_Date,Age,Gender,Region,Disease,Symptoms_Count,Severity_Score,BMI,Blood_Pressure_Systolic,Cholesterol_mg_dL,Blood_Glucose_mg_dL,Smoking_Status,Hospitalized,Hospital_Days,Treatment_Cost_USD,Outcome
19995,P017070,2024-02-04,53,Male,Suburban,Diabetes,6,10,26.9,153,216.0,126.0,Former,Yes,11,4714.59,Improving
19996,P006518,2024-04-21,1,Female,Urban,Pneumonia,9,5,24.1,125,174.0,79.0,Never,No,0,926.29,Stable
19997,P010736,2025-10-04,58,Male,Rural,Diabetes,4,10,29.1,178,215.0,236.0,Current,No,0,1469.97,Improving
19998,P001078,2025-09-27,55,Female,Rural,Coronary Heart Disease,4,7,30.5,132,169.0,119.0,Never,Yes,8,4069.92,Complications
19999,P018916,2023-08-11,37,Male,Urban,Arthritis,6,4,27.5,125,200.0,116.0,Never,No,0,475.76,Recovered

In [10]:
#tells how many values are missing in each column
df.isnull().sum()

Patient_ID                   0
Visit_Date                   0
Age                          0
Gender                       0
Region                       0
Disease                      0
Symptoms_Count               0
Severity_Score               0
BMI                        500
Blood_Pressure_Systolic      0
Cholesterol_mg_dL          684
Blood_Glucose_mg_dL        591
Smoking_Status             338
Hospitalized                 0
Hospital_Days                0
Treatment_Cost_USD         245
Outcome                      0
dtype: int64

In [12]:
#tells the percentage of missing values(for example 2.5 means 2.5% values are missing.meaning 2.5 values not present out of 100 values)
df.isnull().mean()*100

Patient_ID                 0.000
Visit_Date                 0.000
Age                        0.000
Gender                     0.000
Region                     0.000
Disease                    0.000
Symptoms_Count             0.000
Severity_Score             0.000
BMI                        2.500
Blood_Pressure_Systolic    0.000
Cholesterol_mg_dL          3.420
Blood_Glucose_mg_dL        2.955
Smoking_Status             1.690
Hospitalized               0.000
Hospital_Days              0.000
Treatment_Cost_USD         1.225
Outcome                    0.000
dtype: float64

In [22]:
# df.duplicated().sum()
df.nunique()

Patient_ID                 19920
Visit_Date                  1096
Age                           95
Gender                         3
Region                         3
Disease                       10
Symptoms_Count                13
Severity_Score                10
BMI                          299
Blood_Pressure_Systolic      124
Cholesterol_mg_dL            245
Blood_Glucose_mg_dL          245
Smoking_Status                 3
Hospitalized                   2
Hospital_Days                 19
Treatment_Cost_USD         19183
Outcome                        5
dtype: int64

In [23]:
df.isnull().sum().sort_values(ascending=False)

Cholesterol_mg_dL          684
Blood_Glucose_mg_dL        591
BMI                        500
Smoking_Status             338
Treatment_Cost_USD         245
Patient_ID                   0
Visit_Date                   0
Gender                       0
Age                          0
Severity_Score               0
Symptoms_Count               0
Disease                      0
Region                       0
Blood_Pressure_Systolic      0
Hospitalized                 0
Hospital_Days                0
Outcome                      0
dtype: int64

In [26]:
df.duplicated().sum()
df[df.duplicated()]

,Patient_ID,Visit_Date,Age,Gender,Region,Disease,Symptoms_Count,Severity_Score,BMI,Blood_Pressure_Systolic,Cholesterol_mg_dL,Blood_Glucose_mg_dL,Smoking_Status,Hospitalized,Hospital_Days,Treatment_Cost_USD,Outcome
525,P002614,2023-08-16,61,Male,Rural,COPD,6,6,23.4,118,184.0,101.0,Current,No,0,1277.39,Complications
1558,P018996,2023-11-06,39,Female,Urban,Hypertension,2,5,22.2,162,219.0,131.0,Never,No,0,707.64,Stable
1787,P002302,2023-08-03,52,Female,Suburban,Diabetes,2,5,34.9,110,190.0,147.0,Never,No,0,721.48,Recovered
2027,P003371,2025-11-13,19,Other,Urban,Influenza,6,5,15.9,111,185.0,84.0,Former,No,0,522.30,Recovered
2587,P003907,2025-09-08,29,Male,Urban,Influenza,6,4,21.3,103,178.0,83.0,Never,No,0,543.19,Improving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19140,P002172,2025-06-16,70,Female,Urban,Coronary Heart Disease,3,8,30.5,171,296.0,105.0,Former,Yes,9,3457.77,Complications
19323,P010503,2024-05-25,48,Female,Suburban,Hypertension,3,7,29.3,175,226.0,164.0,Current,Yes,10,4356.50,Complications
19554,P015844,2023-03-14,50,Male,Suburban,COPD,7,8,26.7,139,189.0,59.0,Never,Yes,10,4950.24,Deceased
19815,P009074,2023-09-14,61,Female,Urban,Influenza,3,4,26.9,127,131.0,95.0,Former,No,0,429.31,Recovered
19862,P012965,2024-12-28,69,Male,Urban,Arthritis,7,9,26.7,161,200.0,NaN,Current,Yes,10,4307.19,Improving

In [30]:
df=df.drop_duplicates()
# df.duplicated().sum()

,Patient_ID,Visit_Date,Age,Gender,Region,Disease,Symptoms_Count,Severity_Score,BMI,Blood_Pressure_Systolic,Cholesterol_mg_dL,Blood_Glucose_mg_dL,Smoking_Status,Hospitalized,Hospital_Days,Treatment_Cost_USD,Outcome
525,P002614,2023-08-16,61,Male,Rural,COPD,6,6,23.4,118,184.0,101.0,Current,No,0,1277.39,Complications
1558,P018996,2023-11-06,39,Female,Urban,Hypertension,2,5,22.2,162,219.0,131.0,Never,No,0,707.64,Stable
1787,P002302,2023-08-03,52,Female,Suburban,Diabetes,2,5,34.9,110,190.0,147.0,Never,No,0,721.48,Recovered
2027,P003371,2025-11-13,19,Other,Urban,Influenza,6,5,15.9,111,185.0,84.0,Former,No,0,522.30,Recovered
2587,P003907,2025-09-08,29,Male,Urban,Influenza,6,4,21.3,103,178.0,83.0,Never,No,0,543.19,Improving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19140,P002172,2025-06-16,70,Female,Urban,Coronary Heart Disease,3,8,30.5,171,296.0,105.0,Former,Yes,9,3457.77,Complications
19323,P010503,2024-05-25,48,Female,Suburban,Hypertension,3,7,29.3,175,226.0,164.0,Current,Yes,10,4356.50,Complications
19554,P015844,2023-03-14,50,Male,Suburban,COPD,7,8,26.7,139,189.0,59.0,Never,Yes,10,4950.24,Deceased
19815,P009074,2023-09-14,61,Female,Urban,Influenza,3,4,26.9,127,131.0,95.0,Former,No,0,429.31,Recovered
19862,P012965,2024-12-28,69,Male,Urban,Arthritis,7,9,26.7,161,200.0,NaN,Current,Yes,10,4307.19,Improving

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.describe()

,Age,Symptoms_Count,Severity_Score,BMI,Blood_Pressure_Systolic,Cholesterol_mg_dL,Blood_Glucose_mg_dL,Hospital_Days,Treatment_Cost_USD
count,19920.000000,19920.000000,19920.000000,19422.000000,19920.000000,19239.000000,19331.000000,19920.000000,19676.000000
mean,51.443474,4.360392,6.670833,27.185661,133.435492,202.604189,116.611919,3.894930,2233.219359
std,18.622927,1.926009,2.066234,5.270643,20.330152,41.126168,40.666749,4.659009,1742.437377
min,1.000000,0.000000,1.000000,15.000000,85.000000,110.000000,55.000000,0.000000,40.000000
25%,40.000000,3.000000,5.000000,23.500000,119.000000,174.000000,89.000000,0.000000,788.990000
50%,54.000000,4.000000,7.000000,27.100000,133.000000,200.000000,108.000000,0.000000,1509.340000
75%,65.000000,6.000000,8.000000,30.700000,147.000000,229.000000,136.000000,8.000000,3572.900000
max,95.000000,12.000000,10.000000,47.300000,210.000000,360.000000,323.000000,18.000000,9050.290000

In [37]:
df[["Age","BMI"]].describe()

                Age           BMI
count  19920.000000  19422.000000
mean      51.443474     27.185661
std       18.622927      5.270643
min        1.000000     15.000000
25%       40.000000     23.500000
50%       54.000000     27.100000
75%       65.000000     30.700000
max       95.000000     47.300000

Question: which disease is most common?

In [41]:
df["Disease"].value_counts()

Disease
Diabetes                  3551
Hypertension              3341
Influenza                 2445
Asthma                    2028
Pneumonia                 2009
Coronary Heart Disease    1950
COPD                      1561
Chronic Kidney Disease    1198
Migraine                   984
Arthritis                  853
Name: count, dtype: int64

In [42]:
df.groupby("Disease")["Severity_Score"].mean().sort_values(ascending=False)

Disease
Coronary Heart Disease    8.503590
Chronic Kidney Disease    8.061770
COPD                      7.586803
Diabetes                  7.461560
Pneumonia                 6.902439
Hypertension              6.705777
Arthritis                 6.631887
Influenza                 5.314110
Asthma                    4.598126
Migraine                  4.123984
Name: Severity_Score, dtype: float64

In [43]:
df.groupby("Disease").agg({
    "Age": "mean",
    "Severity_Score": "mean",
    "Hospital_Days": "mean",
    "Treatment_Cost_USD": "mean"
}).sort_values("Severity_Score", ascending=False)

,Age,Severity_Score,Hospital_Days,Treatment_Cost_USD
Disease,,,,
Coronary Heart Disease,63.471795,8.503590,6.107692,3772.815636
Chronic Kidney Disease,60.107679,8.061770,5.767112,3424.156960
COPD,65.557976,7.586803,5.323511,3051.302700
Diabetes,55.347226,7.461560,4.204168,2392.772437
Pneumonia,47.936784,6.902439,4.384769,2532.399378
Hypertension,58.261000,6.705777,3.586651,1980.310993
Arthritis,61.944900,6.631887,3.889801,2079.566896
Influenza,36.969325,5.314110,2.425358,1275.608218
Asthma,30.929980,4.598126,1.922584,1127.428529
Migraine,33.730691,4.123984,1.615854,888.453412